import {ClientTenant} from "./types";

export const DEFAULT_CLIENT_TENANT: Partial<ClientTenant> = {
  description: "Arma tu catálogo ferretero y recibe pedidos via WhatsApp",
  keywords: "ferreteros, app, catalogo, online, whatsapp, delivery, pedidos, shop, tienda",
  country: "PE",
  title: "Tu catálogo ferretero fácil",
  phone: "",
  phonePersonal: "",
  color: "teal",
  createdAt: 1670897400000,
  updatedAt: 1670897400000,
  layout: "portrait",
  promoText: "AHORRAS",
  featuredText: "Destacados",
  typeTenant: "test",
  showMqo: false,
  fakeVisitors: false,
  flags: [],
  fields: [],
  mercadopago: false,
  location: null,
  place: "",
  placeUrl: "",
};
